### ISSUE TITLE
there is no PitSimSpigotDependencies-1-all.jar 

### ISSUE THREAD

**Issue by hulajiao** [PitSim-Network/PitSim#2]
Hello, I recently built the PieSim project, but I found that I was missing some local dependencies, which caused me to fail to build successfully. As for the PitSimSpigotDependencies-1-all.jar, I did not find this dependency in the PieSim repository. You can upload it to Warehouse or send me a copy? Thank you so much

**Comment by wiji1** [comment]
Contact me on discord. (@wiji1)
